baseurl = "https://sergeizheleznov.github.io/"
languageCode = "en-us"
title = "Index"
summaryLength = 50

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"

[params]
  author = "Sergei Zheleznov"
  description = ""
  date_format = "Mon Jan 02, 2006"